services:
  frontend:
    build: ./frontend
    container_name: lama_frontend
    restart: always
    ports:
      - "5173:5173"
    networks:
      - lama-network

  backend:
    build: ./backend
    container_name: lama_backend
    restart: always
    ports:
      - "8001:8000"
    depends_on:
      - lamadb
    networks:
      - lama-network

  lamadb:
    image: postgres:16
    container_name: lamadb
    restart: always
    environment:
      POSTGRES_DB: lamadb
      POSTGRES_USER: lamauser
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - lamadb_data:/var/lib/postgresql/data
    networks:
      - lama-network

  nginx:
    image: nginx:alpine
    container_name: lama_nginx
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    networks:
      - lama-network

networks:
  lama-network:
    driver: bridge

volumes:
  lamadb_data: