# Generated by Django 5.2.11 on 2026-02-08 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapLayerModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('layerName', models.CharField(max_length=255, unique=True)),
                ('layerDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegendConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legend_name', models.CharField(blank=True, max_length=255, null=True)),
                ('legend_color', models.CharField(blank=True, max_length=255, null=True)),
                ('legend_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapConfig.maplayermodel')),
            ],
        ),
    ]
