events {}

http {
  resolver 127.0.0.11 valid=10s;

  server {
    listen 8080;
    location / {
      proxy_pass http://frontend:5173;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /vedas/ {
      proxy_pass https://vedas.sac.gov.in/;

      proxy_set_header Host vedas.sac.gov.in;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_ssl_server_name on;
      proxy_buffering off;
    }

     location /geoserver/ {
      proxy_pass https://vedas.sac.gov.in/geoserver/;

      proxy_set_header Host vedas.sac.gov.in;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_ssl_server_name on;
      proxy_buffering off;
    }
    location /ridam/ {
      proxy_pass https://vedas.sac.gov.in/ridam/;

      proxy_set_header Host vedas.sac.gov.in;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_ssl_server_name on;
      proxy_buffering off;
    }
    location /mmi/ {
      proxy_pass https://atlas.mapmyindia.com/;
      proxy_set_header Host atlas.mapmyindia.com;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # CORS headers (critical for browser)
      add_header 'Access-Control-Allow-Origin' '*' always;
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
      add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;

      # Handle OPTIONS preflight
      if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain; charset=utf-8';
        add_header 'Content-Length' 0;
        return 204;
      }

      proxy_ssl_server_name on;
      proxy_buffering off;
    }
  }
}