events {}

http {
  resolver 127.0.0.11 valid=10s;

  server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
    location / {
      proxy_pass http://frontend:5173;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location /vedas/ {
      proxy_pass https://vedas.sac.gov.in/;

      proxy_set_header Host vedas.sac.gov.in;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_ssl_server_name on;
      proxy_buffering off;
      proxy_hide_header X-Frame-Options;
      proxy_hide_header Content-Security-Policy;

      add_header X-Frame-Options "ALLOWALL" always;
      add_header Content-Security-Policy "frame-ancestors *" always;
      sub_filter_types text/html text/css application/javascript;
      sub_filter 'href="/' 'href="/vedas/';
      sub_filter 'src="/' 'src="/vedas/';
      sub_filter_once off;
    }
  }
}